version: '3'
services:  
  web:
    build: .
    environment:
      PYTHONPATH: /app
      FLASK_APP: main.py
      DB_NAME: users
      DB_HOST: users_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      ENVIRONMENT: local-with-docker
    ports:
        - "5001:5001"
    volumes:
        - ./src:/src
    depends_on:
      users_db:
        condition: service_healthy
  users_db:
    image: postgres
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    
  